services:
  mydb:
    image: mysql:latest
    container_name: mydb
    restart: always
    environment:

      MYSQL_ROOT_PASSWORD: root_password  # ✅ Mot de passe root
      MYSQL_DATABASE: django_db  # ✅ Correspond à 'NAME' dans settings.py
      MYSQL_USER: django_user  # ✅ Correspond à 'USER' dans settings.py
      MYSQL_PASSWORD: django_password  # ✅ Correspond à 'PASSWORD' dans settings.py
    ports:
      - "24217:3306"
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  djangoapp:
    build: .
    container_name: djangoapp23217
    command: >
      sh -c "cd /app &&
      python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/app
    working_dir: /app
    ports:
      - "23217:8000"
    depends_on:
      mydb:
        condition: service_healthy
